/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 12:09:15 PM WEST 
//


package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountID" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTGLAccountID"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}AccountDescription"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}OpeningDebitBalance"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}OpeningCreditBalance"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}ClosingDebitBalance"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}ClosingCreditBalance"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GroupingCategory"/>
 *         &lt;element name="GroupingCode" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTGLAccountID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountID",
    "accountDescription",
    "openingDebitBalance",
    "openingCreditBalance",
    "closingDebitBalance",
    "closingCreditBalance",
    "groupingCategory",
    "groupingCode"
})
@XmlRootElement(name = "GeneralLedger")
public class GeneralLedger
    implements ToString
{

    @XmlElement(name = "AccountID", required = true)
    protected String accountID;
    @XmlElement(name = "AccountDescription", required = true)
    protected String accountDescription;
    @XmlElement(name = "OpeningDebitBalance", required = true)
    protected BigDecimal openingDebitBalance;
    @XmlElement(name = "OpeningCreditBalance", required = true)
    protected BigDecimal openingCreditBalance;
    @XmlElement(name = "ClosingDebitBalance", required = true)
    protected BigDecimal closingDebitBalance;
    @XmlElement(name = "ClosingCreditBalance", required = true)
    protected BigDecimal closingCreditBalance;
    @XmlElement(name = "GroupingCategory", required = true)
    protected String groupingCategory;
    @XmlElement(name = "GroupingCode")
    protected String groupingCode;

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the accountDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountDescription() {
        return accountDescription;
    }

    /**
     * Sets the value of the accountDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountDescription(String value) {
        this.accountDescription = value;
    }

    /**
     * Gets the value of the openingDebitBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpeningDebitBalance() {
        return openingDebitBalance;
    }

    /**
     * Sets the value of the openingDebitBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpeningDebitBalance(BigDecimal value) {
        this.openingDebitBalance = value;
    }

    /**
     * Gets the value of the openingCreditBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpeningCreditBalance() {
        return openingCreditBalance;
    }

    /**
     * Sets the value of the openingCreditBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpeningCreditBalance(BigDecimal value) {
        this.openingCreditBalance = value;
    }

    /**
     * Gets the value of the closingDebitBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClosingDebitBalance() {
        return closingDebitBalance;
    }

    /**
     * Sets the value of the closingDebitBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClosingDebitBalance(BigDecimal value) {
        this.closingDebitBalance = value;
    }

    /**
     * Gets the value of the closingCreditBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClosingCreditBalance() {
        return closingCreditBalance;
    }

    /**
     * Sets the value of the closingCreditBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClosingCreditBalance(BigDecimal value) {
        this.closingCreditBalance = value;
    }

    /**
     * Gets the value of the groupingCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupingCategory() {
        return groupingCategory;
    }

    /**
     * Sets the value of the groupingCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupingCategory(String value) {
        this.groupingCategory = value;
    }

    /**
     * Gets the value of the groupingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupingCode() {
        return groupingCode;
    }

    /**
     * Sets the value of the groupingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupingCode(String value) {
        this.groupingCode = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theAccountID;
            theAccountID = this.getAccountID();
            strategy.appendField(locator, this, "accountID", buffer, theAccountID);
        }
        {
            String theAccountDescription;
            theAccountDescription = this.getAccountDescription();
            strategy.appendField(locator, this, "accountDescription", buffer, theAccountDescription);
        }
        {
            BigDecimal theOpeningDebitBalance;
            theOpeningDebitBalance = this.getOpeningDebitBalance();
            strategy.appendField(locator, this, "openingDebitBalance", buffer, theOpeningDebitBalance);
        }
        {
            BigDecimal theOpeningCreditBalance;
            theOpeningCreditBalance = this.getOpeningCreditBalance();
            strategy.appendField(locator, this, "openingCreditBalance", buffer, theOpeningCreditBalance);
        }
        {
            BigDecimal theClosingDebitBalance;
            theClosingDebitBalance = this.getClosingDebitBalance();
            strategy.appendField(locator, this, "closingDebitBalance", buffer, theClosingDebitBalance);
        }
        {
            BigDecimal theClosingCreditBalance;
            theClosingCreditBalance = this.getClosingCreditBalance();
            strategy.appendField(locator, this, "closingCreditBalance", buffer, theClosingCreditBalance);
        }
        {
            String theGroupingCategory;
            theGroupingCategory = this.getGroupingCategory();
            strategy.appendField(locator, this, "groupingCategory", buffer, theGroupingCategory);
        }
        {
            String theGroupingCode;
            theGroupingCode = this.getGroupingCode();
            strategy.appendField(locator, this, "groupingCode", buffer, theGroupingCode);
        }
        return buffer;
    }

}
