/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.08.09 at 02:35:19 PM WEST
//

package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.premiumminds.billy.portugal.services.export.saftpt.schema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _CurrencyAmount_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CurrencyAmount");
	private final static QName _OpeningDebitBalance_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "OpeningDebitBalance");
	private final static QName _RecordID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "RecordID");
	private final static QName _InvoiceDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "InvoiceDate");
	private final static QName _ClosingCreditBalance_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ClosingCreditBalance");
	private final static QName _ProductDescription_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductDescription");
	private final static QName _ProductType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductType");
	private final static QName _TransactionID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TransactionID");
	private final static QName _LineNumber_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "LineNumber");
	private final static QName _CreditAmount_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CreditAmount");
	private final static QName _BillingAddress_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "BillingAddress");
	private final static QName _SourceDocumentID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SourceDocumentID");
	private final static QName _TaxExpirationDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxExpirationDate");
	private final static QName _UnitPrice_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "UnitPrice");
	private final static QName _DateCreated_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "DateCreated");
	private final static QName _FiscalYear_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "FiscalYear");
	private final static QName _SourceBilling_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SourceBilling");
	private final static QName _DeliveryDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "DeliveryDate");
	private final static QName _SupplierTaxID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SupplierTaxID");
	private final static QName _TaxAccountingBasis_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxAccountingBasis");
	private final static QName _MovementDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementDate");
	private final static QName _Reference_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Reference");
	private final static QName _GroupingCategory_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "GroupingCategory");
	private final static QName _ProductNumberCode_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductNumberCode");
	private final static QName _ExchangeRate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ExchangeRate");
	private final static QName _TaxType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxType");
	private final static QName _ProductGroup_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductGroup");
	private final static QName _EndDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "EndDate");
	private final static QName _OriginatingON_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "OriginatingON");
	private final static QName _InvoiceType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "InvoiceType");
	private final static QName _WorkDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "WorkDate");
	private final static QName _ProductID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductID");
	private final static QName _TaxPercentage_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxPercentage");
	private final static QName _DocumentNumber_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "DocumentNumber");
	private final static QName _AccountDescription_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "AccountDescription");
	private final static QName _AuditFileVersion_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "AuditFileVersion");
	private final static QName _Reason_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Reason");
	private final static QName _WithholdingTaxType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "WithholdingTaxType");
	private final static QName _TaxPayable_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxPayable");
	private final static QName _InvoiceNo_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "InvoiceNo");
	private final static QName _NumberOfMovementLines_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01",
			"NumberOfMovementLines");
	private final static QName _Region_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Region");
	private final static QName _ShipFromAddress_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ShipFromAddress");
	private final static QName _CurrencyCode_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CurrencyCode");
	private final static QName _DebitAmount_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "DebitAmount");
	private final static QName _CompanyName_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CompanyName");
	private final static QName _TotalDebit_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TotalDebit");
	private final static QName _MovementType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementType");
	private final static QName _Contact_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Contact");
	private final static QName _Fax_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Fax");
	private final static QName _Website_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Website");
	private final static QName _Description_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Description");
	private final static QName _Quantity_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Quantity");
	private final static QName _OrderDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "OrderDate");
	private final static QName _DocArchivalNumber_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "DocArchivalNumber");
	private final static QName _ClosingDebitBalance_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ClosingDebitBalance");
	private final static QName _BuildingNumber_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "BuildingNumber");
	private final static QName _GLPostingDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "GLPostingDate");
	private final static QName _InvoiceStatusDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "InvoiceStatusDate");
	private final static QName _AddressDetail_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "AddressDetail");
	private final static QName _NumberOfEntries_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "NumberOfEntries");
	private final static QName _PostalCode_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "PostalCode");
	private final static QName _SettlementAmount_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SettlementAmount");
	private final static QName _SourceID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SourceID");
	private final static QName _TaxVerificationDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxVerificationDate");
	private final static QName _ATDocCodeID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ATDocCodeID");
	private final static QName _EACCode_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "EACCode");
	private final static QName _DeliveryID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "DeliveryID");
	private final static QName _ProductCompanyTaxID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductCompanyTaxID");
	private final static QName _TransactionDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TransactionDate");
	private final static QName _TaxCode_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxCode");
	private final static QName _WorkStatus_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "WorkStatus");
	private final static QName _TaxCountryRegion_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxCountryRegion");
	private final static QName _SupplierID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SupplierID");
	private final static QName _InvoiceStatus_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "InvoiceStatus");
	private final static QName _ShipTo_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ShipTo");
	private final static QName _NetTotal_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "NetTotal");
	private final static QName _MovementStatus_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementStatus");
	private final static QName _CustomerTaxID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CustomerTaxID");
	private final static QName _MovementComments_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementComments");
	private final static QName _WorkStatusDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "WorkStatusDate");
	private final static QName _StartDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "StartDate");
	private final static QName _Hash_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Hash");
	private final static QName _Country_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Country");
	private final static QName _TaxAmount_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxAmount");
	private final static QName _MovementEndTime_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementEndTime");
	private final static QName _TaxEntity_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxEntity");
	private final static QName _TaxExemptionReason_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxExemptionReason");
	private final static QName _WarehouseID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "WarehouseID");
	private final static QName _ProductCode_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductCode");
	private final static QName _AccountID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "AccountID");
	private final static QName _ProductVersion_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ProductVersion");
	private final static QName _TaxPointDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TaxPointDate");
	private final static QName _HashControl_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "HashControl");
	private final static QName _CustomerID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CustomerID");
	private final static QName _Email_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Email");
	private final static QName _StreetName_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "StreetName");
	private final static QName _TotalCredit_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TotalCredit");
	private final static QName _OpeningCreditBalance_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "OpeningCreditBalance");
	private final static QName _PaymentMechanism_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "PaymentMechanism");
	private final static QName _JournalID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "JournalID");
	private final static QName _TransactionType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TransactionType");
	private final static QName _CompanyAddress_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CompanyAddress");
	private final static QName _SelfBillingIndicator_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SelfBillingIndicator");
	private final static QName _Telephone_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Telephone");
	private final static QName _Period_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Period");
	private final static QName _GrossTotal_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "GrossTotal");
	private final static QName _MovementStartTime_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementStartTime");
	private final static QName _ShipToAddress_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ShipToAddress");
	private final static QName _UnitOfMeasure_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "UnitOfMeasure");
	private final static QName _LocationID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "LocationID");
	private final static QName _HeaderComment_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "HeaderComment");
	private final static QName _ShipFrom_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "ShipFrom");
	private final static QName _City_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "City");
	private final static QName _BusinessName_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "BusinessName");
	private final static QName _SystemEntryDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "SystemEntryDate");
	private final static QName _CompanyID_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "CompanyID");
	private final static QName _WorkType_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "WorkType");
	private final static QName _SoftwareCertificateNumber_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01",
			"SoftwareCertificateNumber");
	private final static QName _MovementStatusDate_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "MovementStatusDate");
	private final static QName _TotalQuantityIssued_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "TotalQuantityIssued");
	private final static QName _Address_QNAME = new QName(
			"urn:OECD:StandardAuditFile-Tax:PT_1.02_01", "Address");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.premiumminds.billy.portugal.services.export.saftpt.schema
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link GeneralLedgerEntries }
	 * 
	 */
	public GeneralLedgerEntries createGeneralLedgerEntries() {
		return new GeneralLedgerEntries();
	}

	/**
	 * Create an instance of {@link SourceDocuments }
	 * 
	 */
	public SourceDocuments createSourceDocuments() {
		return new SourceDocuments();
	}

	/**
	 * Create an instance of {@link AuditFile }
	 * 
	 */
	public AuditFile createAuditFile() {
		return new AuditFile();
	}

	/**
	 * Create an instance of {@link SourceDocuments.WorkingDocuments }
	 * 
	 */
	public SourceDocuments.WorkingDocuments createSourceDocumentsWorkingDocuments() {
		return new SourceDocuments.WorkingDocuments();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.WorkingDocuments.WorkDocument }
	 * 
	 */
	public SourceDocuments.WorkingDocuments.WorkDocument createSourceDocumentsWorkingDocumentsWorkDocument() {
		return new SourceDocuments.WorkingDocuments.WorkDocument();
	}

	/**
	 * Create an instance of {@link SourceDocuments.MovementOfGoods }
	 * 
	 */
	public SourceDocuments.MovementOfGoods createSourceDocumentsMovementOfGoods() {
		return new SourceDocuments.MovementOfGoods();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.MovementOfGoods.StockMovement }
	 * 
	 */
	public SourceDocuments.MovementOfGoods.StockMovement createSourceDocumentsMovementOfGoodsStockMovement() {
		return new SourceDocuments.MovementOfGoods.StockMovement();
	}

	/**
	 * Create an instance of {@link SourceDocuments.SalesInvoices }
	 * 
	 */
	public SourceDocuments.SalesInvoices createSourceDocumentsSalesInvoices() {
		return new SourceDocuments.SalesInvoices();
	}

	/**
	 * Create an instance of {@link SourceDocuments.SalesInvoices.Invoice }
	 * 
	 */
	public SourceDocuments.SalesInvoices.Invoice createSourceDocumentsSalesInvoicesInvoice() {
		return new SourceDocuments.SalesInvoices.Invoice();
	}

	/**
	 * Create an instance of {@link GeneralLedgerEntries.Journal }
	 * 
	 */
	public GeneralLedgerEntries.Journal createGeneralLedgerEntriesJournal() {
		return new GeneralLedgerEntries.Journal();
	}

	/**
	 * Create an instance of {@link GeneralLedgerEntries.Journal.Transaction }
	 * 
	 */
	public GeneralLedgerEntries.Journal.Transaction createGeneralLedgerEntriesJournalTransaction() {
		return new GeneralLedgerEntries.Journal.Transaction();
	}

	/**
	 * Create an instance of {@link GeneralLedger }
	 * 
	 */
	public GeneralLedger createGeneralLedger() {
		return new GeneralLedger();
	}

	/**
	 * Create an instance of {@link ShippingPointStructure }
	 * 
	 */
	public ShippingPointStructure createShippingPointStructure() {
		return new ShippingPointStructure();
	}

	/**
	 * Create an instance of {@link TaxTable }
	 * 
	 */
	public TaxTable createTaxTable() {
		return new TaxTable();
	}

	/**
	 * Create an instance of {@link TaxTableEntry }
	 * 
	 */
	public TaxTableEntry createTaxTableEntry() {
		return new TaxTableEntry();
	}

	/**
	 * Create an instance of {@link AddressStructurePT }
	 * 
	 */
	public AddressStructurePT createAddressStructurePT() {
		return new AddressStructurePT();
	}

	/**
	 * Create an instance of {@link Header }
	 * 
	 */
	public Header createHeader() {
		return new Header();
	}

	/**
	 * Create an instance of {@link AddressStructure }
	 * 
	 */
	public AddressStructure createAddressStructure() {
		return new AddressStructure();
	}

	/**
	 * Create an instance of {@link Product }
	 * 
	 */
	public Product createProduct() {
		return new Product();
	}

	/**
	 * Create an instance of {@link AuditFile.MasterFiles }
	 * 
	 */
	public AuditFile.MasterFiles createAuditFileMasterFiles() {
		return new AuditFile.MasterFiles();
	}

	/**
	 * Create an instance of {@link Customer }
	 * 
	 */
	public Customer createCustomer() {
		return new Customer();
	}

	/**
	 * Create an instance of {@link Supplier }
	 * 
	 */
	public Supplier createSupplier() {
		return new Supplier();
	}

	/**
	 * Create an instance of {@link SupplierAddressStructure }
	 * 
	 */
	public SupplierAddressStructure createSupplierAddressStructure() {
		return new SupplierAddressStructure();
	}

	/**
	 * Create an instance of {@link WithholdingTax }
	 * 
	 */
	public WithholdingTax createWithholdingTax() {
		return new WithholdingTax();
	}

	/**
	 * Create an instance of {@link Settlement }
	 * 
	 */
	public Settlement createSettlement() {
		return new Settlement();
	}

	/**
	 * Create an instance of {@link Payment }
	 * 
	 */
	public Payment createPayment() {
		return new Payment();
	}

	/**
	 * Create an instance of {@link References }
	 * 
	 */
	public References createReferences() {
		return new References();
	}

	/**
	 * Create an instance of {@link MovementTax }
	 * 
	 */
	public MovementTax createMovementTax() {
		return new MovementTax();
	}

	/**
	 * Create an instance of {@link Currency }
	 * 
	 */
	public Currency createCurrency() {
		return new Currency();
	}

	/**
	 * Create an instance of {@link OrderReferences }
	 * 
	 */
	public OrderReferences createOrderReferences() {
		return new OrderReferences();
	}

	/**
	 * Create an instance of {@link Tax }
	 * 
	 */
	public Tax createTax() {
		return new Tax();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.WorkingDocuments.WorkDocument.DocumentStatus }
	 * 
	 */
	public SourceDocuments.WorkingDocuments.WorkDocument.DocumentStatus createSourceDocumentsWorkingDocumentsWorkDocumentDocumentStatus() {
		return new SourceDocuments.WorkingDocuments.WorkDocument.DocumentStatus();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.WorkingDocuments.WorkDocument.Line }
	 * 
	 */
	public SourceDocuments.WorkingDocuments.WorkDocument.Line createSourceDocumentsWorkingDocumentsWorkDocumentLine() {
		return new SourceDocuments.WorkingDocuments.WorkDocument.Line();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.WorkingDocuments.WorkDocument.DocumentTotals }
	 * 
	 */
	public SourceDocuments.WorkingDocuments.WorkDocument.DocumentTotals createSourceDocumentsWorkingDocumentsWorkDocumentDocumentTotals() {
		return new SourceDocuments.WorkingDocuments.WorkDocument.DocumentTotals();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.MovementOfGoods.StockMovement.DocumentStatus }
	 * 
	 */
	public SourceDocuments.MovementOfGoods.StockMovement.DocumentStatus createSourceDocumentsMovementOfGoodsStockMovementDocumentStatus() {
		return new SourceDocuments.MovementOfGoods.StockMovement.DocumentStatus();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.MovementOfGoods.StockMovement.Line }
	 * 
	 */
	public SourceDocuments.MovementOfGoods.StockMovement.Line createSourceDocumentsMovementOfGoodsStockMovementLine() {
		return new SourceDocuments.MovementOfGoods.StockMovement.Line();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.MovementOfGoods.StockMovement.DocumentTotals }
	 * 
	 */
	public SourceDocuments.MovementOfGoods.StockMovement.DocumentTotals createSourceDocumentsMovementOfGoodsStockMovementDocumentTotals() {
		return new SourceDocuments.MovementOfGoods.StockMovement.DocumentTotals();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.SalesInvoices.Invoice.DocumentStatus }
	 * 
	 */
	public SourceDocuments.SalesInvoices.Invoice.DocumentStatus createSourceDocumentsSalesInvoicesInvoiceDocumentStatus() {
		return new SourceDocuments.SalesInvoices.Invoice.DocumentStatus();
	}

	/**
	 * Create an instance of {@link SourceDocuments.SalesInvoices.Invoice.Line }
	 * 
	 */
	public SourceDocuments.SalesInvoices.Invoice.Line createSourceDocumentsSalesInvoicesInvoiceLine() {
		return new SourceDocuments.SalesInvoices.Invoice.Line();
	}

	/**
	 * Create an instance of
	 * {@link SourceDocuments.SalesInvoices.Invoice.DocumentTotals }
	 * 
	 */
	public SourceDocuments.SalesInvoices.Invoice.DocumentTotals createSourceDocumentsSalesInvoicesInvoiceDocumentTotals() {
		return new SourceDocuments.SalesInvoices.Invoice.DocumentTotals();
	}

	/**
	 * Create an instance of
	 * {@link GeneralLedgerEntries.Journal.Transaction.Line }
	 * 
	 */
	public GeneralLedgerEntries.Journal.Transaction.Line createGeneralLedgerEntriesJournalTransactionLine() {
		return new GeneralLedgerEntries.Journal.Transaction.Line();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CurrencyAmount")
	public JAXBElement<BigDecimal> createCurrencyAmount(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._CurrencyAmount_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "OpeningDebitBalance")
	public JAXBElement<BigDecimal> createOpeningDebitBalance(BigDecimal value) {
		return new JAXBElement<BigDecimal>(
				ObjectFactory._OpeningDebitBalance_QNAME, BigDecimal.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "RecordID")
	public JAXBElement<String> createRecordID(String value) {
		return new JAXBElement<String>(ObjectFactory._RecordID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "InvoiceDate")
	public JAXBElement<XMLGregorianCalendar> createInvoiceDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._InvoiceDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ClosingCreditBalance")
	public JAXBElement<BigDecimal> createClosingCreditBalance(BigDecimal value) {
		return new JAXBElement<BigDecimal>(
				ObjectFactory._ClosingCreditBalance_QNAME, BigDecimal.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductDescription")
	public JAXBElement<String> createProductDescription(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductDescription_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductType")
	public JAXBElement<String> createProductType(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TransactionID")
	public JAXBElement<String> createTransactionID(String value) {
		return new JAXBElement<String>(ObjectFactory._TransactionID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "LineNumber")
	public JAXBElement<BigInteger> createLineNumber(BigInteger value) {
		return new JAXBElement<BigInteger>(ObjectFactory._LineNumber_QNAME,
				BigInteger.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CreditAmount")
	public JAXBElement<BigDecimal> createCreditAmount(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._CreditAmount_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AddressStructure }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "BillingAddress")
	public JAXBElement<AddressStructure> createBillingAddress(
			AddressStructure value) {
		return new JAXBElement<AddressStructure>(
				ObjectFactory._BillingAddress_QNAME, AddressStructure.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SourceDocumentID")
	public JAXBElement<String> createSourceDocumentID(String value) {
		return new JAXBElement<String>(ObjectFactory._SourceDocumentID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxExpirationDate")
	public JAXBElement<XMLGregorianCalendar> createTaxExpirationDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._TaxExpirationDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "UnitPrice")
	public JAXBElement<BigDecimal> createUnitPrice(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._UnitPrice_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "DateCreated")
	public JAXBElement<XMLGregorianCalendar> createDateCreated(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._DateCreated_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "FiscalYear")
	public JAXBElement<Integer> createFiscalYear(Integer value) {
		return new JAXBElement<Integer>(ObjectFactory._FiscalYear_QNAME,
				Integer.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SourceBilling")
	public JAXBElement<String> createSourceBilling(String value) {
		return new JAXBElement<String>(ObjectFactory._SourceBilling_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "DeliveryDate")
	public JAXBElement<XMLGregorianCalendar> createDeliveryDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._DeliveryDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SupplierTaxID")
	public JAXBElement<String> createSupplierTaxID(String value) {
		return new JAXBElement<String>(ObjectFactory._SupplierTaxID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxAccountingBasis")
	public JAXBElement<String> createTaxAccountingBasis(String value) {
		return new JAXBElement<String>(ObjectFactory._TaxAccountingBasis_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementDate")
	public JAXBElement<XMLGregorianCalendar> createMovementDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._MovementDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Reference")
	public JAXBElement<String> createReference(String value) {
		return new JAXBElement<String>(ObjectFactory._Reference_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "GroupingCategory")
	public JAXBElement<String> createGroupingCategory(String value) {
		return new JAXBElement<String>(ObjectFactory._GroupingCategory_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductNumberCode")
	public JAXBElement<String> createProductNumberCode(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductNumberCode_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ExchangeRate")
	public JAXBElement<BigDecimal> createExchangeRate(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._ExchangeRate_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxType")
	public JAXBElement<String> createTaxType(String value) {
		return new JAXBElement<String>(ObjectFactory._TaxType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductGroup")
	public JAXBElement<String> createProductGroup(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductGroup_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "EndDate")
	public JAXBElement<XMLGregorianCalendar> createEndDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._EndDate_QNAME, XMLGregorianCalendar.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "OriginatingON")
	public JAXBElement<String> createOriginatingON(String value) {
		return new JAXBElement<String>(ObjectFactory._OriginatingON_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "InvoiceType")
	public JAXBElement<String> createInvoiceType(String value) {
		return new JAXBElement<String>(ObjectFactory._InvoiceType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "WorkDate")
	public JAXBElement<XMLGregorianCalendar> createWorkDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._WorkDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductID")
	public JAXBElement<String> createProductID(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxPercentage")
	public JAXBElement<BigDecimal> createTaxPercentage(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._TaxPercentage_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "DocumentNumber")
	public JAXBElement<String> createDocumentNumber(String value) {
		return new JAXBElement<String>(ObjectFactory._DocumentNumber_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "AccountDescription")
	public JAXBElement<String> createAccountDescription(String value) {
		return new JAXBElement<String>(ObjectFactory._AccountDescription_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "AuditFileVersion")
	public JAXBElement<String> createAuditFileVersion(String value) {
		return new JAXBElement<String>(ObjectFactory._AuditFileVersion_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Reason")
	public JAXBElement<String> createReason(String value) {
		return new JAXBElement<String>(ObjectFactory._Reason_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "WithholdingTaxType")
	public JAXBElement<String> createWithholdingTaxType(String value) {
		return new JAXBElement<String>(ObjectFactory._WithholdingTaxType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxPayable")
	public JAXBElement<BigDecimal> createTaxPayable(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._TaxPayable_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "InvoiceNo")
	public JAXBElement<String> createInvoiceNo(String value) {
		return new JAXBElement<String>(ObjectFactory._InvoiceNo_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "NumberOfMovementLines")
	public JAXBElement<BigInteger> createNumberOfMovementLines(BigInteger value) {
		return new JAXBElement<BigInteger>(
				ObjectFactory._NumberOfMovementLines_QNAME, BigInteger.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Region")
	public JAXBElement<String> createRegion(String value) {
		return new JAXBElement<String>(ObjectFactory._Region_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AddressStructure }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ShipFromAddress")
	public JAXBElement<AddressStructure> createShipFromAddress(
			AddressStructure value) {
		return new JAXBElement<AddressStructure>(
				ObjectFactory._ShipFromAddress_QNAME, AddressStructure.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CurrencyCode")
	public JAXBElement<String> createCurrencyCode(String value) {
		return new JAXBElement<String>(ObjectFactory._CurrencyCode_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "DebitAmount")
	public JAXBElement<BigDecimal> createDebitAmount(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._DebitAmount_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CompanyName")
	public JAXBElement<String> createCompanyName(String value) {
		return new JAXBElement<String>(ObjectFactory._CompanyName_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TotalDebit")
	public JAXBElement<BigDecimal> createTotalDebit(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._TotalDebit_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementType")
	public JAXBElement<String> createMovementType(String value) {
		return new JAXBElement<String>(ObjectFactory._MovementType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Contact")
	public JAXBElement<String> createContact(String value) {
		return new JAXBElement<String>(ObjectFactory._Contact_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Fax")
	public JAXBElement<String> createFax(String value) {
		return new JAXBElement<String>(ObjectFactory._Fax_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Website")
	public JAXBElement<String> createWebsite(String value) {
		return new JAXBElement<String>(ObjectFactory._Website_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Description")
	public JAXBElement<String> createDescription(String value) {
		return new JAXBElement<String>(ObjectFactory._Description_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Quantity")
	public JAXBElement<BigDecimal> createQuantity(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._Quantity_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "OrderDate")
	public JAXBElement<XMLGregorianCalendar> createOrderDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._OrderDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "DocArchivalNumber")
	public JAXBElement<String> createDocArchivalNumber(String value) {
		return new JAXBElement<String>(ObjectFactory._DocArchivalNumber_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ClosingDebitBalance")
	public JAXBElement<BigDecimal> createClosingDebitBalance(BigDecimal value) {
		return new JAXBElement<BigDecimal>(
				ObjectFactory._ClosingDebitBalance_QNAME, BigDecimal.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "BuildingNumber")
	public JAXBElement<String> createBuildingNumber(String value) {
		return new JAXBElement<String>(ObjectFactory._BuildingNumber_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "GLPostingDate")
	public JAXBElement<XMLGregorianCalendar> createGLPostingDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._GLPostingDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "InvoiceStatusDate")
	public JAXBElement<XMLGregorianCalendar> createInvoiceStatusDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._InvoiceStatusDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "AddressDetail")
	public JAXBElement<String> createAddressDetail(String value) {
		return new JAXBElement<String>(ObjectFactory._AddressDetail_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "NumberOfEntries")
	public JAXBElement<BigInteger> createNumberOfEntries(BigInteger value) {
		return new JAXBElement<BigInteger>(
				ObjectFactory._NumberOfEntries_QNAME, BigInteger.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "PostalCode")
	public JAXBElement<String> createPostalCode(String value) {
		return new JAXBElement<String>(ObjectFactory._PostalCode_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SettlementAmount")
	public JAXBElement<BigDecimal> createSettlementAmount(BigDecimal value) {
		return new JAXBElement<BigDecimal>(
				ObjectFactory._SettlementAmount_QNAME, BigDecimal.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SourceID")
	public JAXBElement<String> createSourceID(String value) {
		return new JAXBElement<String>(ObjectFactory._SourceID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxVerificationDate")
	public JAXBElement<XMLGregorianCalendar> createTaxVerificationDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._TaxVerificationDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ATDocCodeID")
	public JAXBElement<String> createATDocCodeID(String value) {
		return new JAXBElement<String>(ObjectFactory._ATDocCodeID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "EACCode")
	public JAXBElement<String> createEACCode(String value) {
		return new JAXBElement<String>(ObjectFactory._EACCode_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "DeliveryID")
	public JAXBElement<String> createDeliveryID(String value) {
		return new JAXBElement<String>(ObjectFactory._DeliveryID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductCompanyTaxID")
	public JAXBElement<String> createProductCompanyTaxID(String value) {
		return new JAXBElement<String>(
				ObjectFactory._ProductCompanyTaxID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TransactionDate")
	public JAXBElement<XMLGregorianCalendar> createTransactionDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._TransactionDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxCode")
	public JAXBElement<String> createTaxCode(String value) {
		return new JAXBElement<String>(ObjectFactory._TaxCode_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "WorkStatus")
	public JAXBElement<String> createWorkStatus(String value) {
		return new JAXBElement<String>(ObjectFactory._WorkStatus_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxCountryRegion")
	public JAXBElement<String> createTaxCountryRegion(String value) {
		return new JAXBElement<String>(ObjectFactory._TaxCountryRegion_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SupplierID")
	public JAXBElement<String> createSupplierID(String value) {
		return new JAXBElement<String>(ObjectFactory._SupplierID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "InvoiceStatus")
	public JAXBElement<String> createInvoiceStatus(String value) {
		return new JAXBElement<String>(ObjectFactory._InvoiceStatus_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link ShippingPointStructure }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ShipTo")
	public JAXBElement<ShippingPointStructure> createShipTo(
			ShippingPointStructure value) {
		return new JAXBElement<ShippingPointStructure>(
				ObjectFactory._ShipTo_QNAME, ShippingPointStructure.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "NetTotal")
	public JAXBElement<BigDecimal> createNetTotal(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._NetTotal_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementStatus")
	public JAXBElement<String> createMovementStatus(String value) {
		return new JAXBElement<String>(ObjectFactory._MovementStatus_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CustomerTaxID")
	public JAXBElement<String> createCustomerTaxID(String value) {
		return new JAXBElement<String>(ObjectFactory._CustomerTaxID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementComments")
	public JAXBElement<String> createMovementComments(String value) {
		return new JAXBElement<String>(ObjectFactory._MovementComments_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "WorkStatusDate")
	public JAXBElement<XMLGregorianCalendar> createWorkStatusDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._WorkStatusDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "StartDate")
	public JAXBElement<XMLGregorianCalendar> createStartDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._StartDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Hash")
	public JAXBElement<String> createHash(String value) {
		return new JAXBElement<String>(ObjectFactory._Hash_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Country")
	public JAXBElement<String> createCountry(String value) {
		return new JAXBElement<String>(ObjectFactory._Country_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxAmount")
	public JAXBElement<BigDecimal> createTaxAmount(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._TaxAmount_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementEndTime")
	public JAXBElement<XMLGregorianCalendar> createMovementEndTime(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._MovementEndTime_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxEntity")
	public JAXBElement<String> createTaxEntity(String value) {
		return new JAXBElement<String>(ObjectFactory._TaxEntity_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxExemptionReason")
	public JAXBElement<String> createTaxExemptionReason(String value) {
		return new JAXBElement<String>(ObjectFactory._TaxExemptionReason_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "WarehouseID")
	public JAXBElement<String> createWarehouseID(String value) {
		return new JAXBElement<String>(ObjectFactory._WarehouseID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductCode")
	public JAXBElement<String> createProductCode(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductCode_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "AccountID")
	public JAXBElement<String> createAccountID(String value) {
		return new JAXBElement<String>(ObjectFactory._AccountID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ProductVersion")
	public JAXBElement<String> createProductVersion(String value) {
		return new JAXBElement<String>(ObjectFactory._ProductVersion_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TaxPointDate")
	public JAXBElement<XMLGregorianCalendar> createTaxPointDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._TaxPointDate_QNAME, XMLGregorianCalendar.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "HashControl")
	public JAXBElement<String> createHashControl(String value) {
		return new JAXBElement<String>(ObjectFactory._HashControl_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CustomerID")
	public JAXBElement<String> createCustomerID(String value) {
		return new JAXBElement<String>(ObjectFactory._CustomerID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Email")
	public JAXBElement<String> createEmail(String value) {
		return new JAXBElement<String>(ObjectFactory._Email_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "StreetName")
	public JAXBElement<String> createStreetName(String value) {
		return new JAXBElement<String>(ObjectFactory._StreetName_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TotalCredit")
	public JAXBElement<BigDecimal> createTotalCredit(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._TotalCredit_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "OpeningCreditBalance")
	public JAXBElement<BigDecimal> createOpeningCreditBalance(BigDecimal value) {
		return new JAXBElement<BigDecimal>(
				ObjectFactory._OpeningCreditBalance_QNAME, BigDecimal.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "PaymentMechanism")
	public JAXBElement<String> createPaymentMechanism(String value) {
		return new JAXBElement<String>(ObjectFactory._PaymentMechanism_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "JournalID")
	public JAXBElement<String> createJournalID(String value) {
		return new JAXBElement<String>(ObjectFactory._JournalID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TransactionType")
	public JAXBElement<String> createTransactionType(String value) {
		return new JAXBElement<String>(ObjectFactory._TransactionType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AddressStructurePT }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CompanyAddress")
	public JAXBElement<AddressStructurePT> createCompanyAddress(
			AddressStructurePT value) {
		return new JAXBElement<AddressStructurePT>(
				ObjectFactory._CompanyAddress_QNAME, AddressStructurePT.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SelfBillingIndicator")
	public JAXBElement<Integer> createSelfBillingIndicator(Integer value) {
		return new JAXBElement<Integer>(
				ObjectFactory._SelfBillingIndicator_QNAME, Integer.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Telephone")
	public JAXBElement<String> createTelephone(String value) {
		return new JAXBElement<String>(ObjectFactory._Telephone_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Period")
	public JAXBElement<Integer> createPeriod(Integer value) {
		return new JAXBElement<Integer>(ObjectFactory._Period_QNAME,
				Integer.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "GrossTotal")
	public JAXBElement<BigDecimal> createGrossTotal(BigDecimal value) {
		return new JAXBElement<BigDecimal>(ObjectFactory._GrossTotal_QNAME,
				BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementStartTime")
	public JAXBElement<XMLGregorianCalendar> createMovementStartTime(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._MovementStartTime_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AddressStructure }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ShipToAddress")
	public JAXBElement<AddressStructure> createShipToAddress(
			AddressStructure value) {
		return new JAXBElement<AddressStructure>(
				ObjectFactory._ShipToAddress_QNAME, AddressStructure.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "UnitOfMeasure")
	public JAXBElement<String> createUnitOfMeasure(String value) {
		return new JAXBElement<String>(ObjectFactory._UnitOfMeasure_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "LocationID")
	public JAXBElement<String> createLocationID(String value) {
		return new JAXBElement<String>(ObjectFactory._LocationID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "HeaderComment")
	public JAXBElement<String> createHeaderComment(String value) {
		return new JAXBElement<String>(ObjectFactory._HeaderComment_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link ShippingPointStructure }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "ShipFrom")
	public JAXBElement<ShippingPointStructure> createShipFrom(
			ShippingPointStructure value) {
		return new JAXBElement<ShippingPointStructure>(
				ObjectFactory._ShipFrom_QNAME, ShippingPointStructure.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "City")
	public JAXBElement<String> createCity(String value) {
		return new JAXBElement<String>(ObjectFactory._City_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "BusinessName")
	public JAXBElement<String> createBusinessName(String value) {
		return new JAXBElement<String>(ObjectFactory._BusinessName_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SystemEntryDate")
	public JAXBElement<XMLGregorianCalendar> createSystemEntryDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._SystemEntryDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "CompanyID")
	public JAXBElement<String> createCompanyID(String value) {
		return new JAXBElement<String>(ObjectFactory._CompanyID_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "WorkType")
	public JAXBElement<String> createWorkType(String value) {
		return new JAXBElement<String>(ObjectFactory._WorkType_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "SoftwareCertificateNumber")
	public JAXBElement<BigInteger> createSoftwareCertificateNumber(
			BigInteger value) {
		return new JAXBElement<BigInteger>(
				ObjectFactory._SoftwareCertificateNumber_QNAME,
				BigInteger.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link XMLGregorianCalendar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "MovementStatusDate")
	public JAXBElement<XMLGregorianCalendar> createMovementStatusDate(
			XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(
				ObjectFactory._MovementStatusDate_QNAME,
				XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "TotalQuantityIssued")
	public JAXBElement<BigDecimal> createTotalQuantityIssued(BigDecimal value) {
		return new JAXBElement<BigDecimal>(
				ObjectFactory._TotalQuantityIssued_QNAME, BigDecimal.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AddressStructure }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", name = "Address")
	public JAXBElement<AddressStructure> createAddress(AddressStructure value) {
		return new JAXBElement<AddressStructure>(ObjectFactory._Address_QNAME,
				AddressStructure.class, null, value);
	}

}
