/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.08.09 at 02:35:19 PM WEST
//

package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

/**
 * <p>
 * Java class for Payment complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}PaymentMechanism"/>
 *         &lt;element name="PaymentAmount" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFmonetaryType"/>
 *         &lt;element name="PaymentDate" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFdateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment", propOrder = { "paymentMechanism", "paymentAmount",
		"paymentDate" })
public class Payment implements ToString {

	@XmlElement(name = "PaymentMechanism", required = true)
	protected String paymentMechanism;
	@XmlElement(name = "PaymentAmount", required = true)
	protected BigDecimal paymentAmount;
	@XmlElement(name = "PaymentDate", required = true)
	protected XMLGregorianCalendar paymentDate;

	/**
	 * Gets the value of the paymentMechanism property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaymentMechanism() {
		return this.paymentMechanism;
	}

	/**
	 * Sets the value of the paymentMechanism property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaymentMechanism(String value) {
		this.paymentMechanism = value;
	}

	/**
	 * Gets the value of the paymentAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	/**
	 * Sets the value of the paymentAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setPaymentAmount(BigDecimal value) {
		this.paymentAmount = value;
	}

	/**
	 * Gets the value of the paymentDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getPaymentDate() {
		return this.paymentDate;
	}

	/**
	 * Sets the value of the paymentDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setPaymentDate(XMLGregorianCalendar value) {
		this.paymentDate = value;
	}

	public String toString() {
		final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
		final StringBuilder buffer = new StringBuilder();
		this.append(null, buffer, strategy);
		return buffer.toString();
	}

	public StringBuilder append(ObjectLocator locator, StringBuilder buffer,
			ToStringStrategy strategy) {
		strategy.appendStart(locator, this, buffer);
		this.appendFields(locator, buffer, strategy);
		strategy.appendEnd(locator, this, buffer);
		return buffer;
	}

	public StringBuilder appendFields(ObjectLocator locator,
			StringBuilder buffer, ToStringStrategy strategy) {
		{
			String thePaymentMechanism;
			thePaymentMechanism = this.getPaymentMechanism();
			strategy.appendField(locator, this, "paymentMechanism", buffer,
					thePaymentMechanism);
		}
		{
			BigDecimal thePaymentAmount;
			thePaymentAmount = this.getPaymentAmount();
			strategy.appendField(locator, this, "paymentAmount", buffer,
					thePaymentAmount);
		}
		{
			XMLGregorianCalendar thePaymentDate;
			thePaymentDate = this.getPaymentDate();
			strategy.appendField(locator, this, "paymentDate", buffer,
					thePaymentDate);
		}
		return buffer;
	}

}
