/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.08.09 at 02:35:19 PM WEST
//

package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

/**
 * <p>
 * Java class for Settlement complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Settlement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SettlementDiscount" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTtextTypeMandatoryMax30Car" minOccurs="0"/>
 *         &lt;element name="SettlementAmount" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFmonetaryType" minOccurs="0"/>
 *         &lt;element name="SettlementDate" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFdateType" minOccurs="0"/>
 *         &lt;element name="PaymentTerms" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTtextTypeMandatoryMax100Car" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Settlement", propOrder = { "settlementDiscount",
		"settlementAmount", "settlementDate", "paymentTerms" })
public class Settlement implements ToString {

	@XmlElement(name = "SettlementDiscount")
	protected String settlementDiscount;
	@XmlElement(name = "SettlementAmount")
	protected BigDecimal settlementAmount;
	@XmlElement(name = "SettlementDate")
	protected XMLGregorianCalendar settlementDate;
	@XmlElement(name = "PaymentTerms")
	protected String paymentTerms;

	/**
	 * Gets the value of the settlementDiscount property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSettlementDiscount() {
		return this.settlementDiscount;
	}

	/**
	 * Sets the value of the settlementDiscount property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSettlementDiscount(String value) {
		this.settlementDiscount = value;
	}

	/**
	 * Gets the value of the settlementAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getSettlementAmount() {
		return this.settlementAmount;
	}

	/**
	 * Sets the value of the settlementAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setSettlementAmount(BigDecimal value) {
		this.settlementAmount = value;
	}

	/**
	 * Gets the value of the settlementDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getSettlementDate() {
		return this.settlementDate;
	}

	/**
	 * Sets the value of the settlementDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setSettlementDate(XMLGregorianCalendar value) {
		this.settlementDate = value;
	}

	/**
	 * Gets the value of the paymentTerms property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaymentTerms() {
		return this.paymentTerms;
	}

	/**
	 * Sets the value of the paymentTerms property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaymentTerms(String value) {
		this.paymentTerms = value;
	}

	public String toString() {
		final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
		final StringBuilder buffer = new StringBuilder();
		this.append(null, buffer, strategy);
		return buffer.toString();
	}

	public StringBuilder append(ObjectLocator locator, StringBuilder buffer,
			ToStringStrategy strategy) {
		strategy.appendStart(locator, this, buffer);
		this.appendFields(locator, buffer, strategy);
		strategy.appendEnd(locator, this, buffer);
		return buffer;
	}

	public StringBuilder appendFields(ObjectLocator locator,
			StringBuilder buffer, ToStringStrategy strategy) {
		{
			String theSettlementDiscount;
			theSettlementDiscount = this.getSettlementDiscount();
			strategy.appendField(locator, this, "settlementDiscount", buffer,
					theSettlementDiscount);
		}
		{
			BigDecimal theSettlementAmount;
			theSettlementAmount = this.getSettlementAmount();
			strategy.appendField(locator, this, "settlementAmount", buffer,
					theSettlementAmount);
		}
		{
			XMLGregorianCalendar theSettlementDate;
			theSettlementDate = this.getSettlementDate();
			strategy.appendField(locator, this, "settlementDate", buffer,
					theSettlementDate);
		}
		{
			String thePaymentTerms;
			thePaymentTerms = this.getPaymentTerms();
			strategy.appendField(locator, this, "paymentTerms", buffer,
					thePaymentTerms);
		}
		return buffer;
	}

}
