/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.08.09 at 02:35:19 PM WEST
//

package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

/**
 * <p>
 * Java class for ShippingPointStructure complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ShippingPointStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DeliveryID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DeliveryDate" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}WarehouseID" minOccurs="0"/>
 *           &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}LocationID" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShippingPointStructure", propOrder = { "deliveryID",
		"deliveryDate", "warehouseIDAndLocationID", "address" })
public class ShippingPointStructure implements ToString {

	@XmlElement(name = "DeliveryID")
	protected List<String> deliveryID;
	@XmlElement(name = "DeliveryDate")
	protected XMLGregorianCalendar deliveryDate;
	@XmlElementRefs({
			@XmlElementRef(name = "WarehouseID", namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", type = JAXBElement.class),
			@XmlElementRef(name = "LocationID", namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.02_01", type = JAXBElement.class) })
	protected List<JAXBElement<String>> warehouseIDAndLocationID;
	@XmlElement(name = "Address")
	protected AddressStructure address;

	/**
	 * Gets the value of the deliveryID property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deliveryID property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeliveryID().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getDeliveryID() {
		if (this.deliveryID == null) {
			this.deliveryID = new ArrayList<String>();
		}
		return this.deliveryID;
	}

	/**
	 * Gets the value of the deliveryDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDeliveryDate() {
		return this.deliveryDate;
	}

	/**
	 * Sets the value of the deliveryDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDeliveryDate(XMLGregorianCalendar value) {
		this.deliveryDate = value;
	}

	/**
	 * Gets the value of the warehouseIDAndLocationID property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the warehouseIDAndLocationID property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getWarehouseIDAndLocationID().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }
	 * {@code <}{@link String }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<String>> getWarehouseIDAndLocationID() {
		if (this.warehouseIDAndLocationID == null) {
			this.warehouseIDAndLocationID = new ArrayList<JAXBElement<String>>();
		}
		return this.warehouseIDAndLocationID;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link AddressStructure }
	 * 
	 */
	public AddressStructure getAddress() {
		return this.address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link AddressStructure }
	 * 
	 */
	public void setAddress(AddressStructure value) {
		this.address = value;
	}

	public String toString() {
		final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
		final StringBuilder buffer = new StringBuilder();
		this.append(null, buffer, strategy);
		return buffer.toString();
	}

	public StringBuilder append(ObjectLocator locator, StringBuilder buffer,
			ToStringStrategy strategy) {
		strategy.appendStart(locator, this, buffer);
		this.appendFields(locator, buffer, strategy);
		strategy.appendEnd(locator, this, buffer);
		return buffer;
	}

	public StringBuilder appendFields(ObjectLocator locator,
			StringBuilder buffer, ToStringStrategy strategy) {
		{
			List<String> theDeliveryID;
			theDeliveryID = (((this.deliveryID != null) && (!this.deliveryID
					.isEmpty())) ? this.getDeliveryID() : null);
			strategy.appendField(locator, this, "deliveryID", buffer,
					theDeliveryID);
		}
		{
			XMLGregorianCalendar theDeliveryDate;
			theDeliveryDate = this.getDeliveryDate();
			strategy.appendField(locator, this, "deliveryDate", buffer,
					theDeliveryDate);
		}
		{
			List<JAXBElement<String>> theWarehouseIDAndLocationID;
			theWarehouseIDAndLocationID = (((this.warehouseIDAndLocationID != null) && (!this.warehouseIDAndLocationID
					.isEmpty())) ? this.getWarehouseIDAndLocationID() : null);
			strategy.appendField(locator, this, "warehouseIDAndLocationID",
					buffer, theWarehouseIDAndLocationID);
		}
		{
			AddressStructure theAddress;
			theAddress = this.getAddress();
			strategy.appendField(locator, this, "address", buffer, theAddress);
		}
		return buffer;
	}

}
