/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.08.09 at 02:35:19 PM WEST
//

package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierID"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}AccountID"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierTaxID"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CompanyName"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Contact" minOccurs="0"/>
 *         &lt;element name="BillingAddress" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierAddressStructure"/>
 *         &lt;element name="ShipFromAddress" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierAddressStructure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Telephone" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Fax" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Email" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Website" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SelfBillingIndicator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "supplierID", "accountID", "supplierTaxID",
		"companyName", "contact", "billingAddress", "shipFromAddress",
		"telephone", "fax", "email", "website", "selfBillingIndicator" })
@XmlRootElement(name = "Supplier")
public class Supplier implements ToString {

	@XmlElement(name = "SupplierID", required = true)
	protected String supplierID;
	@XmlElement(name = "AccountID", required = true)
	protected String accountID;
	@XmlElement(name = "SupplierTaxID", required = true)
	protected String supplierTaxID;
	@XmlElement(name = "CompanyName", required = true)
	protected String companyName;
	@XmlElement(name = "Contact")
	protected String contact;
	@XmlElement(name = "BillingAddress", required = true)
	protected SupplierAddressStructure billingAddress;
	@XmlElement(name = "ShipFromAddress")
	protected List<SupplierAddressStructure> shipFromAddress;
	@XmlElement(name = "Telephone")
	protected String telephone;
	@XmlElement(name = "Fax")
	protected String fax;
	@XmlElement(name = "Email")
	protected String email;
	@XmlElement(name = "Website")
	protected String website;
	@XmlElement(name = "SelfBillingIndicator")
	protected int selfBillingIndicator;

	/**
	 * Gets the value of the supplierID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSupplierID() {
		return this.supplierID;
	}

	/**
	 * Sets the value of the supplierID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSupplierID(String value) {
		this.supplierID = value;
	}

	/**
	 * Gets the value of the accountID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccountID() {
		return this.accountID;
	}

	/**
	 * Sets the value of the accountID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAccountID(String value) {
		this.accountID = value;
	}

	/**
	 * Gets the value of the supplierTaxID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSupplierTaxID() {
		return this.supplierTaxID;
	}

	/**
	 * Sets the value of the supplierTaxID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSupplierTaxID(String value) {
		this.supplierTaxID = value;
	}

	/**
	 * Gets the value of the companyName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyName() {
		return this.companyName;
	}

	/**
	 * Sets the value of the companyName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompanyName(String value) {
		this.companyName = value;
	}

	/**
	 * Gets the value of the contact property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContact() {
		return this.contact;
	}

	/**
	 * Sets the value of the contact property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContact(String value) {
		this.contact = value;
	}

	/**
	 * Gets the value of the billingAddress property.
	 * 
	 * @return possible object is {@link SupplierAddressStructure }
	 * 
	 */
	public SupplierAddressStructure getBillingAddress() {
		return this.billingAddress;
	}

	/**
	 * Sets the value of the billingAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link SupplierAddressStructure }
	 * 
	 */
	public void setBillingAddress(SupplierAddressStructure value) {
		this.billingAddress = value;
	}

	/**
	 * Gets the value of the shipFromAddress property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the shipFromAddress property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getShipFromAddress().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SupplierAddressStructure }
	 * 
	 * 
	 */
	public List<SupplierAddressStructure> getShipFromAddress() {
		if (this.shipFromAddress == null) {
			this.shipFromAddress = new ArrayList<SupplierAddressStructure>();
		}
		return this.shipFromAddress;
	}

	/**
	 * Gets the value of the telephone property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTelephone() {
		return this.telephone;
	}

	/**
	 * Sets the value of the telephone property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTelephone(String value) {
		this.telephone = value;
	}

	/**
	 * Gets the value of the fax property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFax() {
		return this.fax;
	}

	/**
	 * Sets the value of the fax property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFax(String value) {
		this.fax = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEmail(String value) {
		this.email = value;
	}

	/**
	 * Gets the value of the website property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWebsite() {
		return this.website;
	}

	/**
	 * Sets the value of the website property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWebsite(String value) {
		this.website = value;
	}

	/**
	 * Gets the value of the selfBillingIndicator property.
	 * 
	 */
	public int getSelfBillingIndicator() {
		return this.selfBillingIndicator;
	}

	/**
	 * Sets the value of the selfBillingIndicator property.
	 * 
	 */
	public void setSelfBillingIndicator(int value) {
		this.selfBillingIndicator = value;
	}

	public String toString() {
		final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
		final StringBuilder buffer = new StringBuilder();
		this.append(null, buffer, strategy);
		return buffer.toString();
	}

	public StringBuilder append(ObjectLocator locator, StringBuilder buffer,
			ToStringStrategy strategy) {
		strategy.appendStart(locator, this, buffer);
		this.appendFields(locator, buffer, strategy);
		strategy.appendEnd(locator, this, buffer);
		return buffer;
	}

	public StringBuilder appendFields(ObjectLocator locator,
			StringBuilder buffer, ToStringStrategy strategy) {
		{
			String theSupplierID;
			theSupplierID = this.getSupplierID();
			strategy.appendField(locator, this, "supplierID", buffer,
					theSupplierID);
		}
		{
			String theAccountID;
			theAccountID = this.getAccountID();
			strategy.appendField(locator, this, "accountID", buffer,
					theAccountID);
		}
		{
			String theSupplierTaxID;
			theSupplierTaxID = this.getSupplierTaxID();
			strategy.appendField(locator, this, "supplierTaxID", buffer,
					theSupplierTaxID);
		}
		{
			String theCompanyName;
			theCompanyName = this.getCompanyName();
			strategy.appendField(locator, this, "companyName", buffer,
					theCompanyName);
		}
		{
			String theContact;
			theContact = this.getContact();
			strategy.appendField(locator, this, "contact", buffer, theContact);
		}
		{
			SupplierAddressStructure theBillingAddress;
			theBillingAddress = this.getBillingAddress();
			strategy.appendField(locator, this, "billingAddress", buffer,
					theBillingAddress);
		}
		{
			List<SupplierAddressStructure> theShipFromAddress;
			theShipFromAddress = (((this.shipFromAddress != null) && (!this.shipFromAddress
					.isEmpty())) ? this.getShipFromAddress() : null);
			strategy.appendField(locator, this, "shipFromAddress", buffer,
					theShipFromAddress);
		}
		{
			String theTelephone;
			theTelephone = this.getTelephone();
			strategy.appendField(locator, this, "telephone", buffer,
					theTelephone);
		}
		{
			String theFax;
			theFax = this.getFax();
			strategy.appendField(locator, this, "fax", buffer, theFax);
		}
		{
			String theEmail;
			theEmail = this.getEmail();
			strategy.appendField(locator, this, "email", buffer, theEmail);
		}
		{
			String theWebsite;
			theWebsite = this.getWebsite();
			strategy.appendField(locator, this, "website", buffer, theWebsite);
		}
		{
			int theSelfBillingIndicator;
			theSelfBillingIndicator = (true ? this.getSelfBillingIndicator()
					: 0);
			strategy.appendField(locator, this, "selfBillingIndicator", buffer,
					theSelfBillingIndicator);
		}
		return buffer;
	}

}
