/**
 * Copyright (C) 2013 Premium Minds.
 *
 * This file is part of billy portugal (PT Pack).
 *
 * billy portugal (PT Pack) is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * billy portugal (PT Pack) is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with billy portugal (PT Pack). If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.08.09 at 02:35:19 PM WEST
//

package com.premiumminds.billy.portugal.services.export.saftpt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

/**
 * <p>
 * Java class for SupplierAddressStructure complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierAddressStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}BuildingNumber" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}StreetName" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}AddressDetail"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}City"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}PostalCode"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Region" minOccurs="0"/>
 *         &lt;element name="Country" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierCountry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierAddressStructure", propOrder = { "buildingNumber",
		"streetName", "addressDetail", "city", "postalCode", "region",
		"country" })
public class SupplierAddressStructure implements ToString {

	@XmlElement(name = "BuildingNumber")
	protected String buildingNumber;
	@XmlElement(name = "StreetName")
	protected String streetName;
	@XmlElement(name = "AddressDetail", required = true)
	protected String addressDetail;
	@XmlElement(name = "City", required = true)
	protected String city;
	@XmlElement(name = "PostalCode", required = true)
	protected String postalCode;
	@XmlElement(name = "Region")
	protected String region;
	@XmlElement(name = "Country", required = true)
	protected String country;

	/**
	 * Gets the value of the buildingNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBuildingNumber() {
		return this.buildingNumber;
	}

	/**
	 * Sets the value of the buildingNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBuildingNumber(String value) {
		this.buildingNumber = value;
	}

	/**
	 * Gets the value of the streetName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStreetName() {
		return this.streetName;
	}

	/**
	 * Sets the value of the streetName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStreetName(String value) {
		this.streetName = value;
	}

	/**
	 * Gets the value of the addressDetail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAddressDetail() {
		return this.addressDetail;
	}

	/**
	 * Sets the value of the addressDetail property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAddressDetail(String value) {
		this.addressDetail = value;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCity() {
		return this.city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the postalCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPostalCode() {
		return this.postalCode;
	}

	/**
	 * Sets the value of the postalCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPostalCode(String value) {
		this.postalCode = value;
	}

	/**
	 * Gets the value of the region property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegion() {
		return this.region;
	}

	/**
	 * Sets the value of the region property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRegion(String value) {
		this.region = value;
	}

	/**
	 * Gets the value of the country property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountry() {
		return this.country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountry(String value) {
		this.country = value;
	}

	public String toString() {
		final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
		final StringBuilder buffer = new StringBuilder();
		this.append(null, buffer, strategy);
		return buffer.toString();
	}

	public StringBuilder append(ObjectLocator locator, StringBuilder buffer,
			ToStringStrategy strategy) {
		strategy.appendStart(locator, this, buffer);
		this.appendFields(locator, buffer, strategy);
		strategy.appendEnd(locator, this, buffer);
		return buffer;
	}

	public StringBuilder appendFields(ObjectLocator locator,
			StringBuilder buffer, ToStringStrategy strategy) {
		{
			String theBuildingNumber;
			theBuildingNumber = this.getBuildingNumber();
			strategy.appendField(locator, this, "buildingNumber", buffer,
					theBuildingNumber);
		}
		{
			String theStreetName;
			theStreetName = this.getStreetName();
			strategy.appendField(locator, this, "streetName", buffer,
					theStreetName);
		}
		{
			String theAddressDetail;
			theAddressDetail = this.getAddressDetail();
			strategy.appendField(locator, this, "addressDetail", buffer,
					theAddressDetail);
		}
		{
			String theCity;
			theCity = this.getCity();
			strategy.appendField(locator, this, "city", buffer, theCity);
		}
		{
			String thePostalCode;
			thePostalCode = this.getPostalCode();
			strategy.appendField(locator, this, "postalCode", buffer,
					thePostalCode);
		}
		{
			String theRegion;
			theRegion = this.getRegion();
			strategy.appendField(locator, this, "region", buffer, theRegion);
		}
		{
			String theCountry;
			theCountry = this.getCountry();
			strategy.appendField(locator, this, "country", buffer, theCountry);
		}
		return buffer;
	}

}
