//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 05:06:02 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:OECD:StandardAuditFile-Tax:PT_1.03_01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.premiumminds.billy.portugal.services.export.saftpt.v1_03_01.schema;
