//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 05:06:02 PM WEST 
//


package com.premiumminds.billy.portugal.services.export.saftpt.v1_03_01.schema;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for Settlement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Settlement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SettlementDiscount" type="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}SAFPTtextTypeMandatoryMax30Car" minOccurs="0"/>
 *         &lt;element name="SettlementAmount" type="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}SAFmonetaryType" minOccurs="0"/>
 *         &lt;element name="SettlementDate" type="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}SAFdateType" minOccurs="0"/>
 *         &lt;element name="PaymentTerms" type="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}SAFPTtextTypeMandatoryMax100Car" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Settlement", propOrder = {
    "settlementDiscount",
    "settlementAmount",
    "settlementDate",
    "paymentTerms"
})
public class Settlement
    implements ToString
{

    @XmlElement(name = "SettlementDiscount")
    protected String settlementDiscount;
    @XmlElement(name = "SettlementAmount")
    protected BigDecimal settlementAmount;
    @XmlElement(name = "SettlementDate")
    protected XMLGregorianCalendar settlementDate;
    @XmlElement(name = "PaymentTerms")
    protected String paymentTerms;

    /**
     * Gets the value of the settlementDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDiscount() {
        return settlementDiscount;
    }

    /**
     * Sets the value of the settlementDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDiscount(String value) {
        this.settlementDiscount = value;
    }

    /**
     * Gets the value of the settlementAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSettlementAmount() {
        return settlementAmount;
    }

    /**
     * Sets the value of the settlementAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSettlementAmount(BigDecimal value) {
        this.settlementAmount = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSettlementDate(XMLGregorianCalendar value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTerms(String value) {
        this.paymentTerms = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theSettlementDiscount;
            theSettlementDiscount = this.getSettlementDiscount();
            strategy.appendField(locator, this, "settlementDiscount", buffer, theSettlementDiscount);
        }
        {
            BigDecimal theSettlementAmount;
            theSettlementAmount = this.getSettlementAmount();
            strategy.appendField(locator, this, "settlementAmount", buffer, theSettlementAmount);
        }
        {
            XMLGregorianCalendar theSettlementDate;
            theSettlementDate = this.getSettlementDate();
            strategy.appendField(locator, this, "settlementDate", buffer, theSettlementDate);
        }
        {
            String thePaymentTerms;
            thePaymentTerms = this.getPaymentTerms();
            strategy.appendField(locator, this, "paymentTerms", buffer, thePaymentTerms);
        }
        return buffer;
    }

}
