//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 05:06:02 PM WEST 
//


package com.premiumminds.billy.portugal.services.export.saftpt.v1_03_01.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for SpecialRegimes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialRegimes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}SelfBillingIndicator"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}CashVATSchemeIndicator"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.03_01}ThirdPartiesBillingIndicator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialRegimes", propOrder = {
    "selfBillingIndicator",
    "cashVATSchemeIndicator",
    "thirdPartiesBillingIndicator"
})
public class SpecialRegimes
    implements ToString
{

    @XmlElement(name = "SelfBillingIndicator")
    protected int selfBillingIndicator;
    @XmlElement(name = "CashVATSchemeIndicator")
    protected int cashVATSchemeIndicator;
    @XmlElement(name = "ThirdPartiesBillingIndicator")
    protected int thirdPartiesBillingIndicator;

    /**
     * Gets the value of the selfBillingIndicator property.
     * 
     */
    public int getSelfBillingIndicator() {
        return selfBillingIndicator;
    }

    /**
     * Sets the value of the selfBillingIndicator property.
     * 
     */
    public void setSelfBillingIndicator(int value) {
        this.selfBillingIndicator = value;
    }

    /**
     * Gets the value of the cashVATSchemeIndicator property.
     * 
     */
    public int getCashVATSchemeIndicator() {
        return cashVATSchemeIndicator;
    }

    /**
     * Sets the value of the cashVATSchemeIndicator property.
     * 
     */
    public void setCashVATSchemeIndicator(int value) {
        this.cashVATSchemeIndicator = value;
    }

    /**
     * Gets the value of the thirdPartiesBillingIndicator property.
     * 
     */
    public int getThirdPartiesBillingIndicator() {
        return thirdPartiesBillingIndicator;
    }

    /**
     * Sets the value of the thirdPartiesBillingIndicator property.
     * 
     */
    public void setThirdPartiesBillingIndicator(int value) {
        this.thirdPartiesBillingIndicator = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            int theSelfBillingIndicator;
            theSelfBillingIndicator = (true?this.getSelfBillingIndicator(): 0);
            strategy.appendField(locator, this, "selfBillingIndicator", buffer, theSelfBillingIndicator);
        }
        {
            int theCashVATSchemeIndicator;
            theCashVATSchemeIndicator = (true?this.getCashVATSchemeIndicator(): 0);
            strategy.appendField(locator, this, "cashVATSchemeIndicator", buffer, theCashVATSchemeIndicator);
        }
        {
            int theThirdPartiesBillingIndicator;
            theThirdPartiesBillingIndicator = (true?this.getThirdPartiesBillingIndicator(): 0);
            strategy.appendField(locator, this, "thirdPartiesBillingIndicator", buffer, theThirdPartiesBillingIndicator);
        }
        return buffer;
    }

}
