//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 04:11:45 PM WEST 
//


package com.premiumminds.billy.portugal.services.export.saftpt.v1_02_01.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Header"/>
 *         &lt;element name="MasterFiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GeneralLedger" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Customer" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Supplier" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Product" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TaxTable" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GeneralLedgerEntries" minOccurs="0"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceDocuments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "masterFiles",
    "generalLedgerEntries",
    "sourceDocuments"
})
@XmlRootElement(name = "AuditFile")
public class AuditFile
    implements ToString
{

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "MasterFiles", required = true)
    protected AuditFile.MasterFiles masterFiles;
    @XmlElement(name = "GeneralLedgerEntries")
    protected GeneralLedgerEntries generalLedgerEntries;
    @XmlElement(name = "SourceDocuments")
    protected SourceDocuments sourceDocuments;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the masterFiles property.
     * 
     * @return
     *     possible object is
     *     {@link AuditFile.MasterFiles }
     *     
     */
    public AuditFile.MasterFiles getMasterFiles() {
        return masterFiles;
    }

    /**
     * Sets the value of the masterFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditFile.MasterFiles }
     *     
     */
    public void setMasterFiles(AuditFile.MasterFiles value) {
        this.masterFiles = value;
    }

    /**
     * Gets the value of the generalLedgerEntries property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralLedgerEntries }
     *     
     */
    public GeneralLedgerEntries getGeneralLedgerEntries() {
        return generalLedgerEntries;
    }

    /**
     * Sets the value of the generalLedgerEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralLedgerEntries }
     *     
     */
    public void setGeneralLedgerEntries(GeneralLedgerEntries value) {
        this.generalLedgerEntries = value;
    }

    /**
     * Gets the value of the sourceDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDocuments }
     *     
     */
    public SourceDocuments getSourceDocuments() {
        return sourceDocuments;
    }

    /**
     * Sets the value of the sourceDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDocuments }
     *     
     */
    public void setSourceDocuments(SourceDocuments value) {
        this.sourceDocuments = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Header theHeader;
            theHeader = this.getHeader();
            strategy.appendField(locator, this, "header", buffer, theHeader);
        }
        {
            AuditFile.MasterFiles theMasterFiles;
            theMasterFiles = this.getMasterFiles();
            strategy.appendField(locator, this, "masterFiles", buffer, theMasterFiles);
        }
        {
            GeneralLedgerEntries theGeneralLedgerEntries;
            theGeneralLedgerEntries = this.getGeneralLedgerEntries();
            strategy.appendField(locator, this, "generalLedgerEntries", buffer, theGeneralLedgerEntries);
        }
        {
            SourceDocuments theSourceDocuments;
            theSourceDocuments = this.getSourceDocuments();
            strategy.appendField(locator, this, "sourceDocuments", buffer, theSourceDocuments);
        }
        return buffer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GeneralLedger" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Customer" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Supplier" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Product" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TaxTable" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "generalLedger",
        "customer",
        "supplier",
        "product",
        "taxTable"
    })
    public static class MasterFiles
        implements ToString
    {

        @XmlElement(name = "GeneralLedger")
        protected List<GeneralLedger> generalLedger;
        @XmlElement(name = "Customer")
        protected List<Customer> customer;
        @XmlElement(name = "Supplier")
        protected List<Supplier> supplier;
        @XmlElement(name = "Product")
        protected List<Product> product;
        @XmlElement(name = "TaxTable")
        protected TaxTable taxTable;

        /**
         * Gets the value of the generalLedger property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the generalLedger property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGeneralLedger().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeneralLedger }
         * 
         * 
         */
        public List<GeneralLedger> getGeneralLedger() {
            if (generalLedger == null) {
                generalLedger = new ArrayList<GeneralLedger>();
            }
            return this.generalLedger;
        }

        /**
         * Gets the value of the customer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Customer }
         * 
         * 
         */
        public List<Customer> getCustomer() {
            if (customer == null) {
                customer = new ArrayList<Customer>();
            }
            return this.customer;
        }

        /**
         * Gets the value of the supplier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supplier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupplier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Supplier }
         * 
         * 
         */
        public List<Supplier> getSupplier() {
            if (supplier == null) {
                supplier = new ArrayList<Supplier>();
            }
            return this.supplier;
        }

        /**
         * Gets the value of the product property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProduct().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Product }
         * 
         * 
         */
        public List<Product> getProduct() {
            if (product == null) {
                product = new ArrayList<Product>();
            }
            return this.product;
        }

        /**
         * Gets the value of the taxTable property.
         * 
         * @return
         *     possible object is
         *     {@link TaxTable }
         *     
         */
        public TaxTable getTaxTable() {
            return taxTable;
        }

        /**
         * Sets the value of the taxTable property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaxTable }
         *     
         */
        public void setTaxTable(TaxTable value) {
            this.taxTable = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            {
                List<GeneralLedger> theGeneralLedger;
                theGeneralLedger = (((this.generalLedger!= null)&&(!this.generalLedger.isEmpty()))?this.getGeneralLedger():null);
                strategy.appendField(locator, this, "generalLedger", buffer, theGeneralLedger);
            }
            {
                List<Customer> theCustomer;
                theCustomer = (((this.customer!= null)&&(!this.customer.isEmpty()))?this.getCustomer():null);
                strategy.appendField(locator, this, "customer", buffer, theCustomer);
            }
            {
                List<Supplier> theSupplier;
                theSupplier = (((this.supplier!= null)&&(!this.supplier.isEmpty()))?this.getSupplier():null);
                strategy.appendField(locator, this, "supplier", buffer, theSupplier);
            }
            {
                List<Product> theProduct;
                theProduct = (((this.product!= null)&&(!this.product.isEmpty()))?this.getProduct():null);
                strategy.appendField(locator, this, "product", buffer, theProduct);
            }
            {
                TaxTable theTaxTable;
                theTaxTable = this.getTaxTable();
                strategy.appendField(locator, this, "taxTable", buffer, theTaxTable);
            }
            return buffer;
        }

    }

}
