//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 04:11:45 PM WEST 
//


package com.premiumminds.billy.portugal.services.export.saftpt.v1_02_01.schema;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}NumberOfEntries"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TotalDebit"/>
 *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TotalCredit"/>
 *         &lt;element name="Journal" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}JournalID"/>
 *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
 *                   &lt;element name="Transaction" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionID"/>
 *                             &lt;element name="Period" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTAccountingPeriod"/>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionDate"/>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceID"/>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DocArchivalNumber"/>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionType"/>
 *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GLPostingDate"/>
 *                             &lt;choice>
 *                               &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CustomerID" minOccurs="0"/>
 *                               &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierID" minOccurs="0"/>
 *                             &lt;/choice>
 *                             &lt;element name="Line" maxOccurs="unbounded" minOccurs="2">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}RecordID"/>
 *                                       &lt;element name="AccountID" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTGLAccountID"/>
 *                                       &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceDocumentID" minOccurs="0"/>
 *                                       &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SystemEntryDate"/>
 *                                       &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
 *                                       &lt;choice>
 *                                         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DebitAmount"/>
 *                                         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CreditAmount"/>
 *                                       &lt;/choice>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numberOfEntries",
    "totalDebit",
    "totalCredit",
    "journal"
})
@XmlRootElement(name = "GeneralLedgerEntries")
public class GeneralLedgerEntries
    implements ToString
{

    @XmlElement(name = "NumberOfEntries", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfEntries;
    @XmlElement(name = "TotalDebit", required = true)
    protected BigDecimal totalDebit;
    @XmlElement(name = "TotalCredit", required = true)
    protected BigDecimal totalCredit;
    @XmlElement(name = "Journal")
    protected List<GeneralLedgerEntries.Journal> journal;

    /**
     * Gets the value of the numberOfEntries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfEntries() {
        return numberOfEntries;
    }

    /**
     * Sets the value of the numberOfEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfEntries(BigInteger value) {
        this.numberOfEntries = value;
    }

    /**
     * Gets the value of the totalDebit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalDebit() {
        return totalDebit;
    }

    /**
     * Sets the value of the totalDebit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalDebit(BigDecimal value) {
        this.totalDebit = value;
    }

    /**
     * Gets the value of the totalCredit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalCredit() {
        return totalCredit;
    }

    /**
     * Sets the value of the totalCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalCredit(BigDecimal value) {
        this.totalCredit = value;
    }

    /**
     * Gets the value of the journal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneralLedgerEntries.Journal }
     * 
     * 
     */
    public List<GeneralLedgerEntries.Journal> getJournal() {
        if (journal == null) {
            journal = new ArrayList<GeneralLedgerEntries.Journal>();
        }
        return this.journal;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            BigInteger theNumberOfEntries;
            theNumberOfEntries = this.getNumberOfEntries();
            strategy.appendField(locator, this, "numberOfEntries", buffer, theNumberOfEntries);
        }
        {
            BigDecimal theTotalDebit;
            theTotalDebit = this.getTotalDebit();
            strategy.appendField(locator, this, "totalDebit", buffer, theTotalDebit);
        }
        {
            BigDecimal theTotalCredit;
            theTotalCredit = this.getTotalCredit();
            strategy.appendField(locator, this, "totalCredit", buffer, theTotalCredit);
        }
        {
            List<GeneralLedgerEntries.Journal> theJournal;
            theJournal = (((this.journal!= null)&&(!this.journal.isEmpty()))?this.getJournal():null);
            strategy.appendField(locator, this, "journal", buffer, theJournal);
        }
        return buffer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}JournalID"/>
     *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
     *         &lt;element name="Transaction" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionID"/>
     *                   &lt;element name="Period" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTAccountingPeriod"/>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionDate"/>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceID"/>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DocArchivalNumber"/>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionType"/>
     *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GLPostingDate"/>
     *                   &lt;choice>
     *                     &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CustomerID" minOccurs="0"/>
     *                     &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierID" minOccurs="0"/>
     *                   &lt;/choice>
     *                   &lt;element name="Line" maxOccurs="unbounded" minOccurs="2">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}RecordID"/>
     *                             &lt;element name="AccountID" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTGLAccountID"/>
     *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceDocumentID" minOccurs="0"/>
     *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SystemEntryDate"/>
     *                             &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
     *                             &lt;choice>
     *                               &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DebitAmount"/>
     *                               &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CreditAmount"/>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "journalID",
        "description",
        "transaction"
    })
    public static class Journal
        implements ToString
    {

        @XmlElement(name = "JournalID", required = true)
        protected String journalID;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Transaction")
        protected List<GeneralLedgerEntries.Journal.Transaction> transaction;

        /**
         * Gets the value of the journalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJournalID() {
            return journalID;
        }

        /**
         * Sets the value of the journalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJournalID(String value) {
            this.journalID = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the transaction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transaction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransaction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeneralLedgerEntries.Journal.Transaction }
         * 
         * 
         */
        public List<GeneralLedgerEntries.Journal.Transaction> getTransaction() {
            if (transaction == null) {
                transaction = new ArrayList<GeneralLedgerEntries.Journal.Transaction>();
            }
            return this.transaction;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            {
                String theJournalID;
                theJournalID = this.getJournalID();
                strategy.appendField(locator, this, "journalID", buffer, theJournalID);
            }
            {
                String theDescription;
                theDescription = this.getDescription();
                strategy.appendField(locator, this, "description", buffer, theDescription);
            }
            {
                List<GeneralLedgerEntries.Journal.Transaction> theTransaction;
                theTransaction = (((this.transaction!= null)&&(!this.transaction.isEmpty()))?this.getTransaction():null);
                strategy.appendField(locator, this, "transaction", buffer, theTransaction);
            }
            return buffer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionID"/>
         *         &lt;element name="Period" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTAccountingPeriod"/>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionDate"/>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceID"/>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DocArchivalNumber"/>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}TransactionType"/>
         *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}GLPostingDate"/>
         *         &lt;choice>
         *           &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CustomerID" minOccurs="0"/>
         *           &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SupplierID" minOccurs="0"/>
         *         &lt;/choice>
         *         &lt;element name="Line" maxOccurs="unbounded" minOccurs="2">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}RecordID"/>
         *                   &lt;element name="AccountID" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTGLAccountID"/>
         *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceDocumentID" minOccurs="0"/>
         *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SystemEntryDate"/>
         *                   &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
         *                   &lt;choice>
         *                     &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DebitAmount"/>
         *                     &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CreditAmount"/>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transactionID",
            "period",
            "transactionDate",
            "sourceID",
            "description",
            "docArchivalNumber",
            "transactionType",
            "glPostingDate",
            "customerID",
            "supplierID",
            "line"
        })
        public static class Transaction
            implements ToString
        {

            @XmlElement(name = "TransactionID", required = true)
            protected String transactionID;
            @XmlElement(name = "Period")
            protected int period;
            @XmlElement(name = "TransactionDate", required = true)
            protected XMLGregorianCalendar transactionDate;
            @XmlElement(name = "SourceID", required = true)
            protected String sourceID;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "DocArchivalNumber", required = true)
            protected String docArchivalNumber;
            @XmlElement(name = "TransactionType", required = true)
            protected String transactionType;
            @XmlElement(name = "GLPostingDate", required = true)
            protected XMLGregorianCalendar glPostingDate;
            @XmlElement(name = "CustomerID")
            protected String customerID;
            @XmlElement(name = "SupplierID")
            protected String supplierID;
            @XmlElement(name = "Line", required = true)
            protected List<GeneralLedgerEntries.Journal.Transaction.Line> line;

            /**
             * Gets the value of the transactionID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionID() {
                return transactionID;
            }

            /**
             * Sets the value of the transactionID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionID(String value) {
                this.transactionID = value;
            }

            /**
             * Gets the value of the period property.
             * 
             */
            public int getPeriod() {
                return period;
            }

            /**
             * Sets the value of the period property.
             * 
             */
            public void setPeriod(int value) {
                this.period = value;
            }

            /**
             * Gets the value of the transactionDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTransactionDate() {
                return transactionDate;
            }

            /**
             * Sets the value of the transactionDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTransactionDate(XMLGregorianCalendar value) {
                this.transactionDate = value;
            }

            /**
             * Gets the value of the sourceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceID() {
                return sourceID;
            }

            /**
             * Sets the value of the sourceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceID(String value) {
                this.sourceID = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the docArchivalNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDocArchivalNumber() {
                return docArchivalNumber;
            }

            /**
             * Sets the value of the docArchivalNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDocArchivalNumber(String value) {
                this.docArchivalNumber = value;
            }

            /**
             * Gets the value of the transactionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionType() {
                return transactionType;
            }

            /**
             * Sets the value of the transactionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionType(String value) {
                this.transactionType = value;
            }

            /**
             * Gets the value of the glPostingDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGLPostingDate() {
                return glPostingDate;
            }

            /**
             * Sets the value of the glPostingDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGLPostingDate(XMLGregorianCalendar value) {
                this.glPostingDate = value;
            }

            /**
             * Gets the value of the customerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerID() {
                return customerID;
            }

            /**
             * Sets the value of the customerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerID(String value) {
                this.customerID = value;
            }

            /**
             * Gets the value of the supplierID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierID() {
                return supplierID;
            }

            /**
             * Sets the value of the supplierID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierID(String value) {
                this.supplierID = value;
            }

            /**
             * Gets the value of the line property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the line property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GeneralLedgerEntries.Journal.Transaction.Line }
             * 
             * 
             */
            public List<GeneralLedgerEntries.Journal.Transaction.Line> getLine() {
                if (line == null) {
                    line = new ArrayList<GeneralLedgerEntries.Journal.Transaction.Line>();
                }
                return this.line;
            }

            public String toString() {
                final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                {
                    String theTransactionID;
                    theTransactionID = this.getTransactionID();
                    strategy.appendField(locator, this, "transactionID", buffer, theTransactionID);
                }
                {
                    int thePeriod;
                    thePeriod = (true?this.getPeriod(): 0);
                    strategy.appendField(locator, this, "period", buffer, thePeriod);
                }
                {
                    XMLGregorianCalendar theTransactionDate;
                    theTransactionDate = this.getTransactionDate();
                    strategy.appendField(locator, this, "transactionDate", buffer, theTransactionDate);
                }
                {
                    String theSourceID;
                    theSourceID = this.getSourceID();
                    strategy.appendField(locator, this, "sourceID", buffer, theSourceID);
                }
                {
                    String theDescription;
                    theDescription = this.getDescription();
                    strategy.appendField(locator, this, "description", buffer, theDescription);
                }
                {
                    String theDocArchivalNumber;
                    theDocArchivalNumber = this.getDocArchivalNumber();
                    strategy.appendField(locator, this, "docArchivalNumber", buffer, theDocArchivalNumber);
                }
                {
                    String theTransactionType;
                    theTransactionType = this.getTransactionType();
                    strategy.appendField(locator, this, "transactionType", buffer, theTransactionType);
                }
                {
                    XMLGregorianCalendar theGLPostingDate;
                    theGLPostingDate = this.getGLPostingDate();
                    strategy.appendField(locator, this, "glPostingDate", buffer, theGLPostingDate);
                }
                {
                    String theCustomerID;
                    theCustomerID = this.getCustomerID();
                    strategy.appendField(locator, this, "customerID", buffer, theCustomerID);
                }
                {
                    String theSupplierID;
                    theSupplierID = this.getSupplierID();
                    strategy.appendField(locator, this, "supplierID", buffer, theSupplierID);
                }
                {
                    List<GeneralLedgerEntries.Journal.Transaction.Line> theLine;
                    theLine = (((this.line!= null)&&(!this.line.isEmpty()))?this.getLine():null);
                    strategy.appendField(locator, this, "line", buffer, theLine);
                }
                return buffer;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}RecordID"/>
             *         &lt;element name="AccountID" type="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SAFPTGLAccountID"/>
             *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SourceDocumentID" minOccurs="0"/>
             *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}SystemEntryDate"/>
             *         &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}Description"/>
             *         &lt;choice>
             *           &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}DebitAmount"/>
             *           &lt;element ref="{urn:OECD:StandardAuditFile-Tax:PT_1.02_01}CreditAmount"/>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "recordID",
                "accountID",
                "sourceDocumentID",
                "systemEntryDate",
                "description",
                "debitAmount",
                "creditAmount"
            })
            public static class Line
                implements ToString
            {

                @XmlElement(name = "RecordID", required = true)
                protected String recordID;
                @XmlElement(name = "AccountID", required = true)
                protected String accountID;
                @XmlElement(name = "SourceDocumentID")
                protected String sourceDocumentID;
                @XmlElement(name = "SystemEntryDate", required = true)
                protected XMLGregorianCalendar systemEntryDate;
                @XmlElement(name = "Description", required = true)
                protected String description;
                @XmlElement(name = "DebitAmount")
                protected BigDecimal debitAmount;
                @XmlElement(name = "CreditAmount")
                protected BigDecimal creditAmount;

                /**
                 * Gets the value of the recordID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRecordID() {
                    return recordID;
                }

                /**
                 * Sets the value of the recordID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRecordID(String value) {
                    this.recordID = value;
                }

                /**
                 * Gets the value of the accountID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAccountID() {
                    return accountID;
                }

                /**
                 * Sets the value of the accountID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAccountID(String value) {
                    this.accountID = value;
                }

                /**
                 * Gets the value of the sourceDocumentID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceDocumentID() {
                    return sourceDocumentID;
                }

                /**
                 * Sets the value of the sourceDocumentID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceDocumentID(String value) {
                    this.sourceDocumentID = value;
                }

                /**
                 * Gets the value of the systemEntryDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getSystemEntryDate() {
                    return systemEntryDate;
                }

                /**
                 * Sets the value of the systemEntryDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setSystemEntryDate(XMLGregorianCalendar value) {
                    this.systemEntryDate = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the debitAmount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getDebitAmount() {
                    return debitAmount;
                }

                /**
                 * Sets the value of the debitAmount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setDebitAmount(BigDecimal value) {
                    this.debitAmount = value;
                }

                /**
                 * Gets the value of the creditAmount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getCreditAmount() {
                    return creditAmount;
                }

                /**
                 * Sets the value of the creditAmount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setCreditAmount(BigDecimal value) {
                    this.creditAmount = value;
                }

                public String toString() {
                    final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
                    final StringBuilder buffer = new StringBuilder();
                    append(null, buffer, strategy);
                    return buffer.toString();
                }

                public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                    strategy.appendStart(locator, this, buffer);
                    appendFields(locator, buffer, strategy);
                    strategy.appendEnd(locator, this, buffer);
                    return buffer;
                }

                public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                    {
                        String theRecordID;
                        theRecordID = this.getRecordID();
                        strategy.appendField(locator, this, "recordID", buffer, theRecordID);
                    }
                    {
                        String theAccountID;
                        theAccountID = this.getAccountID();
                        strategy.appendField(locator, this, "accountID", buffer, theAccountID);
                    }
                    {
                        String theSourceDocumentID;
                        theSourceDocumentID = this.getSourceDocumentID();
                        strategy.appendField(locator, this, "sourceDocumentID", buffer, theSourceDocumentID);
                    }
                    {
                        XMLGregorianCalendar theSystemEntryDate;
                        theSystemEntryDate = this.getSystemEntryDate();
                        strategy.appendField(locator, this, "systemEntryDate", buffer, theSystemEntryDate);
                    }
                    {
                        String theDescription;
                        theDescription = this.getDescription();
                        strategy.appendField(locator, this, "description", buffer, theDescription);
                    }
                    {
                        BigDecimal theDebitAmount;
                        theDebitAmount = this.getDebitAmount();
                        strategy.appendField(locator, this, "debitAmount", buffer, theDebitAmount);
                    }
                    {
                        BigDecimal theCreditAmount;
                        theCreditAmount = this.getCreditAmount();
                        strategy.appendField(locator, this, "creditAmount", buffer, theCreditAmount);
                    }
                    return buffer;
                }

            }

        }

    }

}
